apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    notified.notifications.argoproj.io: '{"on-deployed:[0].zxM90Et6k4Elb1-fHdjtDJq0xR0:lifecycle:":1768555861}'
  name: ceph-configmap-3.0.4-tst
  namespace: argocd
spec:
  destination:
    namespace: ceph
    server: https://sd-dev-cc.k8s-api:16443
  project: 3.0.4-tst
  source:
    path: config/overlays/3.0.4-tst/ceph
    repoURL: https://bitbucket.org/okestrolab/config-mgmt.git
    targetRevision: main
  syncPolicy: {}
