apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    notified.notifications.argoproj.io: '{"on-deployed:[0].zxM90Et6k4Elb1-fHdjtDJq0xR0:lifecycle:":1769132111}'
  name: contrabass-collector-3.0.4-bf-gs-con
  namespace: argocd
spec:
  destination:
    namespace: contrabass
    server: https://gs-contrabass-k8s-api.okestro-k8s.com:16443
  project: 3.0.4-gs-contrabass
  source:
    path: 2-products/2.2-contrabass/contrabass-collector/overlays/admin/gs-v4
    repoURL: https://bitbucket.org/okestrolab/maestro-packaging.git
    targetRevision: dev
  syncPolicy: {}
