apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    notified.notifications.argoproj.io: '{"on-deployed:[0].zxM90Et6k4Elb1-fHdjtDJq0xR0:lifecycle:":1773020461}'
  name: contrabass-api-gateway-bf-tst
  namespace: argocd
spec:
  destination:
    namespace: contrabass
    server: https://pq-tst-bf.k8s-api:16443
  project: bf-tst
  source:
    path: 2-products/2.2-contrabass/contrabass-api-gateway/overlays/admin/bf-tst
    repoURL: https://bitbucket.org/okestrolab/maestro-packaging.git
    targetRevision: dev
  syncPolicy: {}
