apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notified.notifications.argoproj.io: '{"on-deployed:[0].zxM90Et6k4Elb1-fHdjtDJq0xR0:lifecycle:":1773817219}'
  name: dev-root-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: 304-cmp-dev
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: 0-installation/argo-application/dev-cmp
    repoURL: https://bitbucket.org/okestrolab/maestro-packaging.git
    targetRevision: HEAD
  syncPolicy: {}
