apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notified.notifications.argoproj.io: '{"on-deployed:[0].zxM90Et6k4Elb1-fHdjtDJq0xR0:lifecycle:":1773120949}'
  name: maestro-remote-app-user-dev-cluster
  namespace: argocd
spec:
  destination:
    namespace: cmp
    server: https://pd-dev-304-cmp.k8s-api:16443
  project: 304-cmp-dev
  source:
    kustomize:
      nameSuffix: -user
      patches:
      - patch: "- op: add \n\n  path: /data/BASE_URL\n  value: dev.portal.okestro.cloud\n"
        target:
          kind: ConfigMap
          name: remote-app-env
    path: 2-products/2.1-maestro/maestro-remote-app/overlays/user/oce/dev
    repoURL: https://bitbucket.org/okestrolab/maestro-packaging.git
    targetRevision: HEAD
  syncPolicy: {}
