apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    notified.notifications.argoproj.io: '{"on-deployed:[0].zxM90Et6k4Elb1-fHdjtDJq0xR0:lifecycle:":1768555897}'
  name: network-collector-tst
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://tst.k8s-api.okestro-k8s.com:16443
  project: validation
  source:
    path: 2-products/2.15-monitoring/network-collector/overlays/admin/oce/tst
    repoURL: https://bitbucket.org/okestrolab/maestro-packaging.git
    targetRevision: dev
  syncPolicy: {}
