apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../../base
    notified.notifications.argoproj.io: '{"on-deployed:[0].zxM90Et6k4Elb1-fHdjtDJq0xR0:lifecycle:":1775023991}'
  name: trb-306-dev-contrabass-scheduler
  namespace: argocd
spec:
  destination:
    name: 306dev-bf
    namespace: contrabass
  project: dev-bf306
  source:
    path: environments/3.0.6/bootfactory/Contrabass/contrabass-scheduler/overlays/dev
    repoURL: http://gitlab.prd.console.trombone.okestro.cloud/yn.yoo/maestro-packaging.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
