apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../../base
    notified.notifications.argoproj.io: '{"on-deployed:[0].zxM90Et6k4Elb1-fHdjtDJq0xR0:lifecycle:":1774588154}'
  name: trb-305-stg-contrabass-admin-service
  namespace: argocd
spec:
  destination:
    namespace: contrabass
    server: https://pq-305tst-bf.k8s-api:16443
  project: stg-bf305
  source:
    path: environments/3.0.5/bootfactory/Contrabass/contrabass-admin-service/overlays/stg
    repoURL: http://gitlab.prd.console.trombone.okestro.cloud/yn.yoo/maestro-packaging.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
