apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    notified.notifications.argoproj.io: '{"on-deployed:[0].zxM90Et6k4Elb1-fHdjtDJq0xR0:lifecycle:":1773719961}'
  name: trb-305-stg-boot-factory-integration
  namespace: argocd
spec:
  destination:
    namespace: boot-factory
    server: https://pq-305tst-bf.k8s-api:16443
  project: stg-bf305
  source:
    path: environments/3.0.5/bootfactory/Bootfactory/boot-factory-integration/overlays/stg
    repoURL: http://gitlab.prd.console.trombone.okestro.cloud/yn.yoo/maestro-packaging.git
    targetRevision: main
  syncPolicy: {}
