apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    notified.notifications.argoproj.io: '{"on-deployed:[0].zxM90Et6k4Elb1-fHdjtDJq0xR0:lifecycle:":1768966521}'
  name: viola-configmap-3.0.5-bf-gs
  namespace: argocd
spec:
  destination:
    namespace: viola
    server: https://gs-viola-k8s-api.okestro-k8s.com:16443
  project: 3.0.4-gs-viola
  source:
    path: config/overlays/3.0.4-bf-gs-viola/viola
    repoURL: https://bitbucket.org/okestrolab/config-mgmt.git
    targetRevision: main
  syncPolicy: {}
